# Generated by Django 4.2.13 on 2024-12-05 05:21

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название документации')),
                ('reg_number', models.PositiveIntegerField(verbose_name='Регистрационный номер')),
                ('approval_date', models.DateField(verbose_name='дата утверждения')),
                ('validity', models.DateField(verbose_name='срок действия')),
                ('approving_authority', models.CharField(max_length=200, verbose_name='Кем утверждено')),
                ('doc_type', models.CharField(blank=True, choices=[('Primary', 'Первичная'), ('Secondary', 'Вторичная')], db_index=True, default='Primary', max_length=200, verbose_name='Тип документа')),
                ('doc_media', models.FileField(blank=True, null=True, upload_to='media')),
            ],
            options={
                'verbose_name': 'Документация',
                'verbose_name_plural': 'Документация',
                'ordering': ['doc_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Фамилия, имя, отчество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='изображение')),
                ('laboratory', models.CharField(max_length=200, verbose_name='Структурное подразделение')),
                ('job_title', models.TextField(blank=True, verbose_name='Должноcть')),
                ('duties', models.TextField(blank=True, verbose_name='Должноcтные обязанности')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название метода')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание метода')),
                ('docs', models.ManyToManyField(blank=True, related_name='methods', to='rabies_immunglobulin.document', verbose_name='Документация с описанием метода')),
            ],
            options={
                'verbose_name': 'Метод контроля',
                'verbose_name_plural': 'Методы контроля',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SpecificationStandart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название спецификационной характеристики')),
                ('index_number', models.PositiveIntegerField(default=0, verbose_name='номер в соответствии с протоколом исследования')),
                ('measure', models.CharField(blank=True, choices=[('No measure', 'Нет размерности'), ('UI', 'Международные единицы в 1 мл'), ('percents', '%'), ('OI', 'Единица оптической плотности'), ('temperature', 'градус Цельсия'), ('ml', 'мл'), ('pH', 'единица рН')], db_index=True, default='No measure', max_length=50, verbose_name='единица измерения')),
                ('reference_description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание характеристики')),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Максимальное значение')),
                ('lower_limit', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Минимальное значение')),
                ('if_sample', models.BooleanField(db_index=True, default=False, verbose_name='Предусмотрен ли стандартный образец')),
                ('methods', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reference_value', to='rabies_immunglobulin.method', verbose_name='Метод определения')),
            ],
            options={
                'verbose_name': 'Нормативное значение показателя качества',
                'verbose_name_plural': 'Нормативные значения показателей качества',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='StandartSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название стандартного образца')),
                ('reg_number', models.PositiveIntegerField(verbose_name='Регистрационный номер')),
                ('value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='Значение определяемой характеристики')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Дополнительные сведения')),
                ('sample_type', models.CharField(blank=True, choices=[('PH', 'Фармакопейный'), ('RF', 'Государственный'), ('OSO', 'Отраслевой'), ('WHO', 'Стандарт ВОЗ'), ('IN_HOUSE', 'Стандарт предприятия'), ('ST_C', 'Образец сравнения')], db_index=True, default='IN_HOUSE', max_length=200, verbose_name='Вид стандартного образца')),
                ('issue_date', models.DateField(verbose_name='дата выпуска')),
                ('best_before_date', models.DateField(verbose_name='срок годности')),
                ('documents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample', to='rabies_immunglobulin.document', verbose_name='документация')),
                ('indicator', models.ManyToManyField(blank=True, null=True, related_name='reference_sample', to='rabies_immunglobulin.specificationstandart', verbose_name='Определяемая характеристика')),
            ],
            options={
                'verbose_name': 'Стандартный образец',
                'verbose_name_plural': 'Стандартные образцы',
                'ordering': ['title', 'reg_number'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер серии')),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='Объем серии')),
                ('ampoules_quantity', models.PositiveSmallIntegerField(blank=True, verbose_name='Количество ампул')),
                ('packs_quantity', models.PositiveSmallIntegerField(blank=True, verbose_name='Количество упаковок')),
                ('issue_date', models.DateField(verbose_name='дата выпуска')),
                ('best_before_date', models.DateField(verbose_name='срок годности')),
                ('docs', models.ManyToManyField(blank=True, related_name='series', to='rabies_immunglobulin.document', verbose_name='документация')),
            ],
            options={
                'verbose_name': 'Производственная серия',
                'verbose_name_plural': 'Производственные серии',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SpecificationParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='Количественное значение')),
                ('measure', models.CharField(blank=True, choices=[('No measure', 'Нет размерности'), ('UI', 'Международные единицы в 1 мл'), ('percents', '%'), ('pH', 'единица рН'), ('OI', 'Единица оптической плотности'), ('temperature', 'градус Цельсия')], db_index=True, default='No measure', max_length=50, verbose_name='Единица измерения')),
                ('description', models.TextField(blank='True', verbose_name='Описание значения')),
                ('begin_control_date', models.DateField(default=datetime.date.today, verbose_name='дата начала контроля')),
                ('end_control_date', models.DateField(default=datetime.date.today, verbose_name='дата проведения контроля')),
                ('media', models.FileField(blank=True, null=True, upload_to='media')),
                ('butch_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batch_parameters', to='rabies_immunglobulin.batch', verbose_name='Номер серии')),
                ('controler', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='control_carry', to='rabies_immunglobulin.employee', verbose_name='Контролер')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='batch_parameter', to='rabies_immunglobulin.specificationstandart', verbose_name='Определяемая характеристика')),
            ],
            options={
                'verbose_name': 'Значение показателя качества производственной серии',
                'verbose_name_plural': 'Значения показателей качества производственных серий',
                'ordering': ['title'],
                'unique_together': {('title', 'butch_series')},
            },
        ),
    ]
