# Generated by Django 4.2.13 on 2024-05-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0005_alter_batch_volume_alter_document_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationparameter',
            name='description',
            field=models.TextField(blank='True', verbose_name='Описание значения'),
        ),
    ]
