# Generated by Django 4.2.13 on 2024-05-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0007_alter_specificationparameter_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationstandart',
            name='lower_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Минимальное значение'),
        ),
    ]
