# Generated by Django 4.2.13 on 2024-05-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0008_alter_specificationstandart_lower_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationstandart',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание характеристики'),
        ),
        migrations.AlterField(
            model_name='specificationstandart',
            name='upper_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальное значение'),
        ),
    ]
