# Generated by Django 4.2.13 on 2024-05-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0009_alter_specificationstandart_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificationparameter',
            name='standart_parameters',
        ),
    ]
