# Generated by Django 4.2.13 on 2024-05-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0011_rename_description_specificationstandart_reference_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationstandart',
            name='deviation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Допустимое отклонение от референс-значения'),
        ),
        migrations.AlterField(
            model_name='specificationstandart',
            name='reference_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
