# Generated by Django 4.2.13 on 2024-06-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0015_alter_specificationparameter_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationstandart',
            name='measure',
            field=models.CharField(blank=True, choices=[(1, 'Нет размерности'), (2, 'Международные единицы'), (3, '%'), (4, 'Единица оптической плотности'), (5, 'градус Цельсия')], db_index=True, default=1, max_length=5, verbose_name='единица измерения'),
        ),
    ]
