# Generated by Django 4.2.13 on 2024-06-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0016_alter_specificationstandart_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationparameter',
            name='measure',
            field=models.CharField(blank=True, choices=[('No measure', 'Нет размерности'), ('UI', 'Международные единицы'), ('percents', '%'), ('OI', 'Единица оптической плотности'), ('temperature', 'градус Цельсия')], db_index=True, default='No measure', max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='specificationstandart',
            name='measure',
            field=models.CharField(blank=True, choices=[('No measure', 'Нет размерности'), ('UI', 'Международные единицы'), ('percents', '%'), ('OI', 'Единица оптической плотности'), ('temperature', 'градус Цельсия')], db_index=True, default='No measure', max_length=50, verbose_name='единица измерения'),
        ),
    ]
