# Generated by Django 4.2.13 on 2024-09-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0021_rename_indicator_2_standartsample_indicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificationparameter',
            name='method_doc',
        ),
    ]
