# Generated by Django 4.2.13 on 2024-09-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0024_alter_specificationparameter_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='title',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Номер серии'),
        ),
    ]
