# Generated by Django 4.2.13 on 2024-11-25 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0032_alter_specificationparameter_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standartsample',
            options={'ordering': ['title', 'reg_number'], 'verbose_name': 'Стандартный образец', 'verbose_name_plural': 'Стандартные образцы'},
        ),
        migrations.AddField(
            model_name='specificationstandart',
            name='if_samples',
            field=models.CharField(blank=True, choices=[('Yes', 'Предусмотрен'), ('No', 'Не предусмотрен'), ('Oth', 'Предусмотрены образцы для сравнения')], db_index=True, default='No', max_length=50, null=True, verbose_name='Предусмотрен ли образец сравнения'),
        ),
        migrations.AddField(
            model_name='standartsample',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Дополнительные сведения'),
        ),
        migrations.AlterField(
            model_name='specificationparameter',
            name='end_control_date',
            field=models.DateField(default=datetime.date.today, verbose_name='дата проведения контроля'),
        ),
        migrations.AlterField(
            model_name='specificationparameter',
            name='measure',
            field=models.CharField(blank=True, choices=[('No measure', 'Нет размерности'), ('UI', 'Международные единицы в 1 мл'), ('percents', '%'), ('OI', 'Единица оптической плотности'), ('temperature', 'градус Цельсия')], db_index=True, default='No measure', max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='specificationstandart',
            name='measure',
            field=models.CharField(blank=True, choices=[('No measure', 'Нет размерности'), ('UI', 'Международные единицы в 1 мл'), ('percents', '%'), ('OI', 'Единица оптической плотности'), ('temperature', 'градус Цельсия'), ('ml', 'мл')], db_index=True, default='No measure', max_length=50, verbose_name='единица измерения'),
        ),
        migrations.AlterField(
            model_name='standartsample',
            name='sample_type',
            field=models.CharField(blank=True, choices=[('PH', 'Фармакопейный'), ('RF', 'Государственный'), ('OSO', 'Отраслевой'), ('WHO', 'Стандарт ВОЗ'), ('IN_HOUSE', 'Стандарт предприятия'), ('ST_C', 'Образец сравнения')], db_index=True, default='IN_HOUSE', max_length=200, verbose_name='Вид стандартного образца'),
        ),
    ]
