# Generated by Django 4.2.13 on 2024-11-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0034_alter_specificationstandart_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standartsample',
            options={'ordering': ['title'], 'verbose_name': 'Стандартный образец', 'verbose_name_plural': 'Стандартные образцы'},
        ),
    ]
