# Generated by Django 4.2.13 on 2024-11-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0036_alter_specificationstandart_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationstandart',
            name='if_sampless',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Предусмотрен ли образец сравнения'),
        ),
    ]
