# Generated by Django 4.2.13 on 2024-11-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0037_specificationstandart_if_sampless'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificationstandart',
            name='if_samples',
        ),
        migrations.AlterField(
            model_name='specificationstandart',
            name='if_sampless',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Предусмотрен ли стандартный образец'),
        ),
    ]
