# Generated by Django 4.2.13 on 2024-11-29 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0038_remove_specificationstandart_if_samples_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificationstandart',
            old_name='if_sampless',
            new_name='if_sample',
        ),
    ]
