# Generated by Django 4.2.13 on 2024-12-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0039_rename_if_sampless_specificationstandart_if_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standartsample',
            name='indicator',
        ),
        migrations.AddField(
            model_name='standartsample',
            name='indicator',
            field=models.ManyToManyField(blank=True, null=True, related_name='reference_sample', to='rabies_immunglobulin.specificationstandart', verbose_name='Определяемая характеристика'),
        ),
    ]
