# Generated by Django 4.2.13 on 2024-12-03 13:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0041_remove_specificationparameter_standart_samples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание метода'),
        ),
    ]
