# Generated by Django 4.2.13 on 2024-12-04 05:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0042_alter_method_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание метода'),
        ),
    ]
