# Generated by Django 4.2.13 on 2024-12-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0043_alter_method_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificationstandart',
            name='if_sample',
        ),
    ]
