# Generated by Django 4.2.13 on 2024-12-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0045_specificationstandart_if_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificationstandart',
            name='if_sample',
        ),
    ]
