# Generated by Django 4.2.13 on 2025-03-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0049_specificationparameter_standart_samples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificationparameter',
            name='standart_samples',
        ),
    ]
