# Generated by Django 4.2.13 on 2025-03-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0050_remove_specificationparameter_standart_samples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standartsample',
            name='indicator',
            field=models.ManyToManyField(related_name='reference_sample', to='rabies_immunglobulin.specificationstandart', verbose_name='Определяемая характеристика'),
        ),
    ]
