# Generated by Django 4.2.13 on 2024-05-24 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='docs',
            field=models.ManyToManyField(blank=True, related_name='methods', to='rabies_immunglobulin.document', verbose_name='Документация с описанием метода'),
        ),
        migrations.AlterField(
            model_name='specificationstandart',
            name='methods',
            field=models.ForeignKey(blank='True', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reference_value', to='rabies_immunglobulin.method', verbose_name='Метод определения'),
        ),
    ]
