# Generated by Django 4.2.13 on 2024-05-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0002_alter_method_docs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='docs',
            field=models.ManyToManyField(blank=True, related_name='series', to='rabies_immunglobulin.document'),
        ),
    ]
