# Generated by Django 4.2.13 on 2024-05-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0003_alter_batch_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='docs',
            field=models.ManyToManyField(blank=True, related_name='series', to='rabies_immunglobulin.document', verbose_name='документация'),
        ),
    ]
