# Generated by Django 4.2.13 on 2024-05-24 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0004_alter_batch_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='Объем серии'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('Primary', 'Первичная'), ('Secondary', 'Вторичная')], db_index=True, default='Primary', max_length=200, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='method',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание метода'),
        ),
        migrations.AlterField(
            model_name='method',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название метода'),
        ),
        migrations.AlterField(
            model_name='specificationparameter',
            name='controler',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='control_carry', to='rabies_immunglobulin.employee', verbose_name='Контролер'),
        ),
        migrations.AlterField(
            model_name='specificationparameter',
            name='measure',
            field=models.CharField(blank=True, choices=[('No measure', 'Нет размерности'), ('UI', 'Международные единицы'), ('percents', '%'), ('OI', 'Единица оптической плотности'), ('temperature', 'градус Цельсия')], db_index=True, default='No measure', max_length=200, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='specificationstandart',
            name='description',
            field=models.CharField(blank='True', max_length=200, null='True', verbose_name='Описание характеристики'),
        ),
        migrations.AlterField(
            model_name='specificationstandart',
            name='lower_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null='True', verbose_name='Минимальное значение'),
        ),
        migrations.AlterField(
            model_name='specificationstandart',
            name='methods',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reference_value', to='rabies_immunglobulin.method', verbose_name='Метод определения'),
        ),
        migrations.AlterField(
            model_name='specificationstandart',
            name='upper_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Максимальное значение'),
        ),
        migrations.AlterField(
            model_name='standartsample',
            name='documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample', to='rabies_immunglobulin.document', verbose_name='документация'),
        ),
        migrations.AlterField(
            model_name='standartsample',
            name='sample_type',
            field=models.CharField(blank=True, choices=[('PH', 'Фармакопейный'), ('RF', 'Государственный'), ('OSO', 'Отраслевой'), ('WHO', 'Стандарт ВОЗ'), ('IN_HOUSE', 'Стандарт предприятия')], db_index=True, default='IN_HOUSE', max_length=200, verbose_name='Вид стандартного образца'),
        ),
        migrations.AlterField(
            model_name='standartsample',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='Значение определяемой характеристики'),
        ),
    ]
