# Generated by Django 4.2.13 on 2024-05-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0010_remove_specificationparameter_standart_parameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificationstandart',
            old_name='description',
            new_name='reference_description',
        ),
        migrations.AddField(
            model_name='specificationstandart',
            name='deviation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Допустимое отклонение от референс-значения'),
        ),
        migrations.AddField(
            model_name='specificationstandart',
            name='reference_value',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Референс-значение'),
        ),
    ]
