# Generated by Django 4.2.13 on 2024-05-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0013_specificationparameter_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationparameter',
            name='measure',
            field=models.CharField(blank=True, choices=[('No measure', 'Нет размерности'), ('UI', 'Международные единицы'), ('percents', '%'), ('OI', 'Единица оптической плотности'), ('temperature', 'градус Цельсия')], db_index=True, default='No measure', max_length=20, verbose_name='Единица измерения'),
        ),
    ]
