# Generated by Django 4.2.13 on 2024-09-04 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0017_alter_specificationparameter_measure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standartsample',
            name='indicator_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reference_sample', to='rabies_immunglobulin.document', verbose_name='Определяемая характеристика'),
        ),
    ]
