# Generated by Django 4.2.13 on 2024-09-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0022_remove_specificationparameter_method_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_media',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
