# Generated by Django 4.2.13 on 2024-09-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0025_alter_batch_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specificationparameter',
            options={'ordering': ['title'], 'verbose_name': 'Значение показателя качества производственной серии', 'verbose_name_plural': 'Значения показателей качества производственных серий'},
        ),
        migrations.RemoveField(
            model_name='specificationstandart',
            name='deviation',
        ),
        migrations.RemoveField(
            model_name='specificationstandart',
            name='reference_value',
        ),
        migrations.AlterField(
            model_name='specificationparameter',
            name='measure',
            field=models.CharField(blank=True, choices=[('No measure', 'Нет размерности'), ('UI', 'Международные единицы в мл'), ('percents', '%'), ('OI', 'Единица оптической плотности'), ('temperature', 'градус Цельсия')], db_index=True, default='No measure', max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='specificationstandart',
            name='lower_limit',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Минимальное значение'),
        ),
        migrations.AlterField(
            model_name='specificationstandart',
            name='measure',
            field=models.CharField(blank=True, choices=[('No measure', 'Нет размерности'), ('UI', 'Международные единицы в мл'), ('percents', '%'), ('OI', 'Единица оптической плотности'), ('temperature', 'градус Цельсия')], db_index=True, default='No measure', max_length=50, verbose_name='единица измерения'),
        ),
        migrations.AlterField(
            model_name='specificationstandart',
            name='reference_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание характеристики'),
        ),
        migrations.AlterField(
            model_name='specificationstandart',
            name='upper_limit',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Максимальное значение'),
        ),
    ]
