# Generated by Django 4.2.13 on 2024-09-12 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0026_alter_specificationparameter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specificationstandart',
            options={'ordering': ['title'], 'verbose_name': 'Нормативное значение показателя качества', 'verbose_name_plural': 'Нормативные значения показателей качества'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='ampoules_quantity',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Количество ампул'),
        ),
        migrations.AlterField(
            model_name='specificationparameter',
            name='control_date',
            field=models.DateField(default=datetime.date.today, verbose_name='дата завершения контроля'),
        ),
    ]
