# Generated by Django 4.2.13 on 2024-09-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0027_alter_specificationstandart_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='packs_quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Количество ампул'),
        ),
    ]
