# Generated by Django 4.2.13 on 2024-09-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0028_batch_packs_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='packs_quantity',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Количество упаковок'),
        ),
    ]
