# Generated by Django 4.2.13 on 2024-09-12 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0029_alter_batch_packs_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificationparameter',
            name='control_date',
        ),
        migrations.AddField(
            model_name='specificationparameter',
            name='end_control_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='дата завершения контроля'),
        ),
    ]
