# Generated by Django 4.2.13 on 2024-09-12 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0030_remove_specificationparameter_control_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationparameter',
            name='begin_control_date',
            field=models.DateField(default=datetime.date.today, verbose_name='дата начала контроля'),
        ),
    ]
