# Generated by Django 4.2.13 on 2024-11-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0033_alter_standartsample_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specificationstandart',
            options={'ordering': ['index_number', 'title'], 'verbose_name': 'Нормативное значение показателя качества', 'verbose_name_plural': 'Нормативные значения показателей качества'},
        ),
        migrations.AddField(
            model_name='specificationstandart',
            name='index_number',
            field=models.PositiveIntegerField(default=0, verbose_name='номер в соответствии с протоколом исследования'),
        ),
        migrations.AlterField(
            model_name='specificationparameter',
            name='measure',
            field=models.CharField(blank=True, choices=[('No measure', 'Нет размерности'), ('UI', 'Международные единицы в 1 мл'), ('percents', '%'), ('pH', 'единица рН'), ('OI', 'Единица оптической плотности'), ('temperature', 'градус Цельсия')], db_index=True, default='No measure', max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='specificationstandart',
            name='if_samples',
            field=models.CharField(blank=True, choices=[('Yes', 'Предусмотрен'), ('No', 'Не предусмотрен')], db_index=True, default='No', max_length=50, null=True, verbose_name='Предусмотрен ли образец сравнения'),
        ),
        migrations.AlterField(
            model_name='specificationstandart',
            name='measure',
            field=models.CharField(blank=True, choices=[('No measure', 'Нет размерности'), ('UI', 'Международные единицы в 1 мл'), ('percents', '%'), ('OI', 'Единица оптической плотности'), ('temperature', 'градус Цельсия'), ('ml', 'мл'), ('pH', 'единица рН')], db_index=True, default='No measure', max_length=50, verbose_name='единица измерения'),
        ),
    ]
