# Generated by Django 4.2.13 on 2025-03-25 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0046_remove_specificationstandart_if_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificationstandart',
            name='index_number',
        ),
        migrations.AddField(
            model_name='specificationparameter',
            name='standart_samples',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='control_appl', to='rabies_immunglobulin.standartsample', verbose_name='Стандартный образец'),
        ),
        migrations.AddField(
            model_name='specificationstandart',
            name='if_samples',
            field=models.CharField(blank=True, choices=[('Yes', 'Предусмотрен'), ('No', 'Не предусмотрен'), ('Oth', 'Предусмотрены образцы для сравнения')], db_index=True, default='No', max_length=50, null=True, verbose_name='Предусмотрен ли образец сравнения'),
        ),
        migrations.AlterField(
            model_name='method',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание метода'),
        ),
        migrations.AlterField(
            model_name='specificationparameter',
            name='measure',
            field=models.CharField(blank=True, choices=[('No measure', 'Нет размерности'), ('UI', 'Международные единицы в 1 мл'), ('percents', '%'), ('OI', 'Единица оптической плотности'), ('temperature', 'градус Цельсия')], db_index=True, default='No measure', max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='specificationstandart',
            name='measure',
            field=models.CharField(blank=True, choices=[('No measure', 'Нет размерности'), ('UI', 'Международные единицы в 1 мл'), ('percents', '%'), ('OI', 'Единица оптической плотности'), ('temperature', 'градус Цельсия'), ('ml', 'мл')], db_index=True, default='No measure', max_length=50, verbose_name='единица измерения'),
        ),
        migrations.RemoveField(
            model_name='standartsample',
            name='indicator',
        ),
        migrations.AddField(
            model_name='standartsample',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reference_sample', to='rabies_immunglobulin.specificationstandart', verbose_name='Определяемая характеристика'),
        ),
    ]
