# Generated by Django 4.2.13 on 2024-09-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0026_alter_specificationparameter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specificationstandart',
            options={'ordering': ['title'], 'verbose_name': 'Нормативное значение показателя качества', 'verbose_name_plural': 'Нормативные значения показателей качества'},
        ),
        migrations.AddField(
            model_name='batch',
            name='packs_quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Количество ампул'),
        ),
        migrations.AddField(
            model_name='specificationparameter',
            name='begin_control_date',
            field=models.DateField(default=None, verbose_name='дата начала контроля'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='ampoules_quantity',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Количество ампул'),
        ),
        migrations.AlterField(
            model_name='specificationparameter',
            name='control_date',
            field=models.DateField(verbose_name='дата завершения контроля'),
        ),
    ]
