# Generated by Django 4.2.13 on 2024-09-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0027_alter_specificationstandart_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificationparameter',
            old_name='control_date',
            new_name='end_control_date',
        ),
    ]
