# Generated by Django 4.2.13 on 2024-09-12 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0028_rename_control_date_specificationparameter_end_control_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='packs_quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Количество ампул'),
        ),
        migrations.AlterField(
            model_name='specificationparameter',
            name='begin_control_date',
            field=models.DateField(default=datetime.date.today, verbose_name='дата начала контроля'),
        ),
        migrations.AlterField(
            model_name='specificationparameter',
            name='end_control_date',
            field=models.DateField(default=datetime.date.today, verbose_name='дата завершения контроля'),
        ),
    ]
