# Generated by Django 4.2.13 on 2024-09-12 12:43

from django.db import migrations
from datetime import date




def copy_batch(apps, schema_editor):
    Batch = apps.get_model('rabies_immunglobulin', 'Batch')
    for batch in Batch.objects.all():
        batch.packs_quantity = 1
        batch.save()


def copy_parameters(apps, schema_editor):
    SpecificationParameter = apps.get_model('rabies_immunglobulin',
                                            'SpecificationParameter')
    for parameter in SpecificationParameter.objects.all():
        parameter. begin_control_date = date.today
        parameter.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rabies_immunglobulin', '0029_alter_batch_packs_quantity_and_more'),
    ]

    operations = [migrations.RunPython(copy_batch),
        migrations.RunPython(copy_parameters)
    ]
